const UIActionTypes = {
	LOAD_LOCAL_STORAGE: 'LOAD_LOCAL_STORAGE',
	FORM_FIELD_CHANGED: 'FORM_FIELD_CHANGED',
	SOURCE_SELECTED: 'SOURCE_SELECTED',
	SOURCE_UNSELECTED: 'SOURCE_UNSELECTED',
	SHOW_ALERT: 'SHOW_ALERT',
	HIDE_ALERT: 'HIDE_ALERT',
	CLEAR_ALERTS: 'CLEAR_ALERTS',
	SEARCH_FORM_SUBMIT: 'SEARCH_FORM_SUBMIT',
	NEW_SEARCH_STARTED: 'NEW_SEARCH_STARTED',
	PANEL_OPENED: 'PANEL_OPENED',
	PANEL_CLOSED: 'PANEL_CLOSED',
	SAVE_RESULT: 'SAVE_RESULT',
	SUBMIT_FEEDBACK: 'SUBMIT_FEEDBACK'
};

const APIActionTypes = {
	GET_SOURCE_LISTS: 'GET_SOURCE_LISTS',
	SOURCE_LISTS_LOADED: 'SOURCE_LISTS_LOADED',
	SET_SOURCES_TO_SEARCH: 'SET_SOURCES_TO_SEARCH',
	CLEAR_SOURCES_TO_SEARCH: 'CLEAR_SOURCES_TO_SEARCH',
	ARTICLE_LISTS_LOADED: 'ARTICLE_LISTS_LOADED',
	RESULT_SAVED: 'RESULT_SAVED',
	RESULT_LOADED: 'RESULT_LOADED',
	FB_INIT_COMPLETE: 'FB_INIT_COMPLETE',
	FB_USER_CHANGED: 'FB_USER_CHANGED',
	SET_FB_USER_DATA: 'SET_FB_USER_DATA',
	CLEAR_FB_USER_DATA: 'CLEAR_FB_USER_DATA'
};

export { UIActionTypes, APIActionTypes };
